-- Seed data for breeds table
-- Generated from breeds.json
-- Usage: psql -d your_database -f seed_breeds.sql

BEGIN;

-- Only insert if table is empty
DO $$
BEGIN
    IF (SELECT COUNT(*) FROM breeds) = 0 THEN
        INSERT INTO breeds (breed) VALUES
            ('affenpinscher'),
            ('african'),
            ('airedale'),
            ('akita'),
            ('appenzeller'),
            ('australian'),
            ('bakharwal'),
            ('basenji'),
            ('beagle'),
            ('bluetick'),
            ('borzoi'),
            ('bouvier'),
            ('boxer'),
            ('brabancon'),
            ('briard'),
            ('buhund'),
            ('bulldog'),
            ('bullterrier'),
            ('cattledog'),
            ('cavapoo'),
            ('chihuahua'),
            ('chippiparai'),
            ('chow'),
            ('clumber'),
            ('cockapoo'),
            ('collie'),
            ('coonhound'),
            ('corgi'),
            ('cotondetulear'),
            ('dachshund'),
            ('dalmatian'),
            ('dane'),
            ('danish'),
            ('deerhound'),
            ('dhole'),
            ('dingo'),
            ('doberman'),
            ('elkhound'),
            ('entlebucher'),
            ('eskimo'),
            ('finnish'),
            ('frise'),
            ('gaddi'),
            ('german'),
            ('greyhound'),
            ('groenendael'),
            ('havanese'),
            ('hound'),
            ('husky'),
            ('keeshond'),
            ('kelpie'),
            ('kombai'),
            ('komondor'),
            ('kuvasz'),
            ('labradoodle'),
            ('labrador'),
            ('leonberg'),
            ('lhasa'),
            ('malamute'),
            ('malinois'),
            ('maltese'),
            ('mastiff'),
            ('mexicanhairless'),
            ('mix'),
            ('mountain'),
            ('mudhol'),
            ('newfoundland'),
            ('otterhound'),
            ('ovcharka'),
            ('papillon'),
            ('pariah'),
            ('pekinese'),
            ('pembroke'),
            ('pinscher'),
            ('pitbull'),
            ('pointer'),
            ('pomeranian'),
            ('poodle'),
            ('pug'),
            ('puggle'),
            ('pyrenees'),
            ('rajapalayam'),
            ('redbone'),
            ('retriever'),
            ('ridgeback'),
            ('rottweiler'),
            ('rough'),
            ('saluki'),
            ('samoyed'),
            ('schipperke'),
            ('schnauzer'),
            ('segugio'),
            ('setter'),
            ('sharpei'),
            ('sheepdog'),
            ('shiba'),
            ('shihtzu'),
            ('spaniel'),
            ('spitz'),
            ('springer'),
            ('stbernard'),
            ('terrier'),
            ('tervuren'),
            ('vizsla'),
            ('waterdog'),
            ('weimaraner'),
            ('whippet'),
            ('wolfhound');
        RAISE NOTICE 'Inserted 108 breeds';
    ELSE
        RAISE NOTICE 'breeds table not empty, skipping seed';
    END IF;
END $$;

COMMIT;
