"""

Revision ID: 14a47eeaad4b
Revises: 6227cebe030c
Create Date: 2026-02-01 17:40:40.512331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a47eeaad4b'
down_revision: Union[str, Sequence[str], None] = '6227cebe030c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_pl', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_descriptions_breed_id'), 'breed_descriptions', ['breed_id'], unique=True)
    op.create_table('variant_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_pl', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['breed_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_descriptions_variant_id'), 'variant_descriptions', ['variant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_descriptions_variant_id'), table_name='variant_descriptions')
    op.drop_table('variant_descriptions')
    op.drop_index(op.f('ix_breed_descriptions_breed_id'), table_name='breed_descriptions')
    op.drop_table('breed_descriptions')
    # ### end Alembic commands ###
