"""init

Revision ID: 6227cebe030c
Revises: 
Create Date: 2026-02-01 17:18:23.792098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6227cebe030c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeds_breed'), 'breeds', ['breed'], unique=True)
    op.create_table('breed_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_variants_breed_id'), 'breed_variants', ['breed_id'], unique=False)
    op.create_index(op.f('ix_breed_variants_variant'), 'breed_variants', ['variant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breed_variants_variant'), table_name='breed_variants')
    op.drop_index(op.f('ix_breed_variants_breed_id'), table_name='breed_variants')
    op.drop_table('breed_variants')
    op.drop_index(op.f('ix_breeds_breed'), table_name='breeds')
    op.drop_table('breeds')
    # ### end Alembic commands ###
